/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hardwarehome;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class itemReg extends javax.swing.JInternalFrame {

    /**
     * Creates new form itemReg
     */
     Connection conn;
ResultSet rs;
PreparedStatement pst;
    public itemReg() {
        initComponents();
        conn=(Connection) newdb.ConnectDb();
        tablelord();
         LocalDate today=LocalDate.now();
         
         da.setText(today.toString());
         
        try{
   String sql="SELECT DISTINCT `fn` FROM `rega`";
   pst=conn.prepareStatement(sql);
   rs=pst.executeQuery();
   while(rs.next()){
     pe.addItem(rs.getString("fn"));
      
   }
   
       }
       catch(Exception e){
       JOptionPane.showMessageDialog(rootPane, e);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ca = new javax.swing.JComboBox<>();
        pe = new javax.swing.JComboBox<>();
        co = new javax.swing.JTextField();
        na = new javax.swing.JTextField();
        qu = new javax.swing.JTextField();
        lo = new javax.swing.JTextField();
        da = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        item = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ca.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        ca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Material", "Tool" }));
        jPanel1.add(ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 180, 40));

        pe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personel", " " }));
        jPanel1.add(pe, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 160, 40));

        co.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        co.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coKeyReleased(evt);
            }
        });
        jPanel1.add(co, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 180, 40));

        na.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(na, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 180, 40));

        qu.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(qu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 180, 40));

        lo.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(lo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 160, 40));

        da.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 160, 40));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel3.setText("Category");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel4.setText("Code");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel5.setText("Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel6.setText("Location");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel7.setText("Date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel8.setText("Personel");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel9.setText("Quantity");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 100, 50));

        jButton2.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 100, 50));

        item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(item);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 277, 900, 200));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 920, 480));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablelord(){
    try{
    String sql="SELECT `ca`, `co`, `na`, `qu`, `lo`, `da`, `pe` FROM `item` ";
    pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
    item.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
    pst.execute();
    }
    catch(Exception e){
    }
    
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(ca.getSelectedItem().equals("Select")|| co.getText().isEmpty()|| na.getText().isEmpty()|| qu.getText().isEmpty()|| lo.getText().isEmpty()|| da.getText().isEmpty()|| pe.getSelectedItem().equals("Personel")){
        JOptionPane.showMessageDialog(null, "Cannot be Empty!!");
        
        }
        else{
        try{
        String sql="insert into item(ca,co,na,qu,lo,da,pe) values(?,?,?,?,?,?,?)";
        pst=conn.prepareStatement(sql);
        
        pst.setString(1, ca.getSelectedItem().toString());
        pst.setString(2, co.getText());
        pst.setString(3, na.getText());
        pst.setString(4, qu.getText());
        pst.setString(5, lo.getText());
        pst.setString(6, da.getText());
        pst.setString(7, pe.getSelectedItem().toString());
        
        pst.execute();
        JOptionPane.showMessageDialog(null, "Success");
        tablelord();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(ca.getSelectedItem().equals("Select")|| co.getText().isEmpty()|| na.getText().isEmpty()|| qu.getText().isEmpty()|| lo.getText().isEmpty()|| da.getText().isEmpty()|| pe.getSelectedItem().equals("Personel")){
        JOptionPane.showMessageDialog(null, "Cannot be Empty!!");
        
        }
        else{
        try{
        String sql="UPDATE item SET ca=?,na=?,qu=?,lo=?,da=?,pe=? WHERE co=?";
        pst=conn.prepareStatement(sql);
        
        pst.setString(1, ca.getSelectedItem().toString());
        
        pst.setString(2, na.getText());
        pst.setString(3, qu.getText());
        pst.setString(4, lo.getText());
        pst.setString(5, da.getText());
        pst.setString(6, pe.getSelectedItem().toString());
        pst.setString(7, co.getText());
        pst.execute();
        JOptionPane.showMessageDialog(null, "Success");
        tablelord();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void coKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coKeyReleased
        // TODO add your handling code here:
        try{
        String sql="SELECT `ca`, `co`, `na`, `qu`, `lo`, `da`, `pe` FROM `item` WHERE co='"+co.getText()+"'";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){
            ca.setSelectedItem(rs.getString("ca"));
            na.setText(rs.getString("na"));
            qu.setText(rs.getString("qu"));
            lo.setText(rs.getString("lo"));
            da.setText(rs.getString("da"));
            pe.setSelectedItem(rs.getString("pe"));
        }
        else{
        ca.setSelectedItem("Select");
        na.setText("");
        qu.setText("");
        lo.setText("");
        
        pe.setSelectedItem("Personel");
        }
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_coKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ca;
    private javax.swing.JTextField co;
    private javax.swing.JTextField da;
    private javax.swing.JTable item;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lo;
    private javax.swing.JTextField na;
    private javax.swing.JComboBox<String> pe;
    private javax.swing.JTextField qu;
    // End of variables declaration//GEN-END:variables
}
