/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hardwarehome;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
 

public class Reg extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reg
     */
    Connection conn;
ResultSet rs;
PreparedStatement pst;
    public Reg() {
        initComponents();
         conn=(Connection) newdb.ConnectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        co = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnKeyReleased(evt);
            }
        });
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 220, 40));

        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        jPanel1.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 220, 40));

        co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coActionPerformed(evt);
            }
        });
        co.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coKeyReleased(evt);
            }
        });
        jPanel1.add(co, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 220, 40));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 220, 40));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel4.setText("Details");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Name_35px_1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Name_35px_1.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Contacts_35px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ID_Verified_35px.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel11.setText("F Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel12.setText("L Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 10));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel13.setText("Contact");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel14.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel14.setText("Id Number");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 380));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Save_35px.png"))); // NOI18N
        jButton1.setText("Save Member");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 220, 60));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Update_User_35px.png"))); // NOI18N
        jButton2.setText("Update Member");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 220, 60));

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Save_35px.png"))); // NOI18N
        jButton3.setText("Save Admin");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 220, 60));

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Update_User_35px.png"))); // NOI18N
        jButton4.setText("Update Admin");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 220, 60));

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 280, 360));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 720, 400));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 740, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(  id.getText().isEmpty()|| fn.getText().isEmpty() || ln.getText().isEmpty()  || co.getText().isEmpty() ){
 JOptionPane.showMessageDialog(null, "Fields cannot be Empty");
 } else{
       try{
            String sql="insert into reg(idn,fn,ln,con) values(?,?,?,?)";
           pst=conn.prepareStatement(sql);
           pst.setString(1, id.getText());
           pst.setString(2, fn.getText());
           pst.setString(3, ln.getText());
          
          pst.setString(4, co.getText());
         
           
           pst.execute();
           JOptionPane.showMessageDialog(null, "Registered Successfully");
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, "Member Exists");
       }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fnKeyReleased

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        // TODO add your handling code here:
         try{
   String sql="SELECT `fn`, `ln`, `con` FROM `reg` WHERE idn='"+id.getText()+"'";
   pst=conn.prepareStatement(sql);
   rs=pst.executeQuery();
   if(rs.next()){
     fn.setText(rs.getString("fn"));
      ln.setText(rs.getString("ln"));
       co.setText(rs.getString("con"));
        
   }
   else{
  
  
   }
       }
       catch(Exception e){
       JOptionPane.showMessageDialog(rootPane, e);
       }
    }//GEN-LAST:event_idKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if( id.getText().isEmpty() || fn.getText().isEmpty() || ln.getText().isEmpty()  || co.getText().isEmpty()){
 JOptionPane.showMessageDialog(null, "Fields cannot be Empty");
 } else{
       try{
            String sql="UPDATE reg SET fn=?,ln=?,con=? WHERE idn=?";
           pst=conn.prepareStatement(sql);
           
           pst.setString(1, fn.getText());
           pst.setString(2, ln.getText());
          
          pst.setString(3, co.getText());
           pst.setString(4, id.getText());
           
           pst.execute();
           JOptionPane.showMessageDialog(null, "Updated Successfully");
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       if(!fn.getText().equals("AdminAdmin")){
       JOptionPane.showMessageDialog(null, "Not Authorised");
       }
        
       else  if(  id.getText().isEmpty()|| fn.getText().isEmpty() || ln.getText().isEmpty()  || co.getText().isEmpty() ){
 JOptionPane.showMessageDialog(null, "Fields cannot be Empty");
 } else{
       try{
            String sql="insert into rega(idn,fn,ln,con) values(?,?,?,?)";
           pst=conn.prepareStatement(sql);
           pst.setString(1, id.getText());
           pst.setString(2, fn.getText());
           pst.setString(3, ln.getText());
          
          pst.setString(4, co.getText());
         
           
           pst.execute();
           JOptionPane.showMessageDialog(null, "Registered Successfully");
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, "Member Exists");
       }}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         if(!fn.getText().equals("AdminAdmin")){
       JOptionPane.showMessageDialog(null, "Not Authorised");
       }
        
       else
         if( id.getText().isEmpty() || fn.getText().isEmpty() || ln.getText().isEmpty()  || co.getText().isEmpty()){
 JOptionPane.showMessageDialog(null, "Fields cannot be Empty");
 } else{
       try{
            String sql="UPDATE rega SET fn=?,ln=?,con=? WHERE idn=?";
           pst=conn.prepareStatement(sql);
           
           pst.setString(1, fn.getText());
           pst.setString(2, ln.getText());
          
          pst.setString(3, co.getText());
           pst.setString(4, id.getText());
           
           pst.execute();
           JOptionPane.showMessageDialog(null, "Updated Successfully");
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void coKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coKeyReleased
        // TODO add your handling code here:
        
         try{
   String sql="SELECT `idn`,`fn`, `ln`, `con` FROM `rega` WHERE con='"+co.getText()+"'";
   pst=conn.prepareStatement(sql);
   rs=pst.executeQuery();
   if(rs.next()){
       id.setText(rs.getString("idn"));
     
      ln.setText(rs.getString("ln"));
       co.setText(rs.getString("con"));
        
   }
   else{
 
  
   }
       }
       catch(Exception e){
       JOptionPane.showMessageDialog(rootPane, e);
       }
    }//GEN-LAST:event_coKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField co;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ln;
    // End of variables declaration//GEN-END:variables
}
